import { expect, test } from '@playwright/test'
import { execFileSync } from 'node:child_process'

test('键盘登录、跳过导航、文件夹导航和菜单与焦点恢复', async ({ page }) => {
  await page.goto('/login')
  const password = page.getByLabel(/^密码/)
  await password.fill('e2e-secret123')
  await password.focus()
  await page.keyboard.press('Tab')
  const visibility = page.getByRole('button', { name: '显示或隐藏密码' })
  await expect(visibility).toBeFocused()
  await page.keyboard.press('Space')
  await expect(password).toHaveAttribute('type', 'text')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByRole('button', { name: '登录', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: '上传', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  const response = await page.request.post('/api/folders', { headers, data: { name: '键盘文件夹' } })
  expect(response.ok()).toBe(true)
  const parent = await response.json()
  expect((await page.request.post('/api/folders', { headers, data: { name: '键盘子文件夹', parent_id: parent.id } })).ok()).toBe(true)
  await page.goto('/library')
  await expect(page.getByRole('link', { name: '键盘文件夹', exact: true })).toBeVisible()
  await page.keyboard.press('Tab')
  const skip = page.getByRole('link', { name: '跳到主要内容' })
  await expect(skip).toBeFocused()
  expect(await skip.evaluate(element => element.getBoundingClientRect().top)).toBeGreaterThanOrEqual(0)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('main')).toBeFocused()
  const folder = page.getByRole('link', { name: '键盘文件夹', exact: true })
  await folder.focus()
  expect(await folder.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('solid')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`folder=${parent.id}$`))
  const expand = page.getByRole('button', { name: '展开或收起 键盘文件夹 的子文件夹' })
  await expand.focus()
  await page.keyboard.press('Space')
  await expect(expand).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('link', { name: '键盘子文件夹', exact: true })).toBeHidden()
  await page.keyboard.press('Space')
  await expect(page.getByRole('link', { name: '键盘子文件夹', exact: true })).toBeVisible()
  const menu = page.getByRole('button', { name: '键盘文件夹的文件夹菜单' })
  await menu.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menuitem', { name: '重命名', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()
  await page.getByRole('button', { name: '未分类', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/folder=root$/)
  for (const button of await page.getByRole('button').all()) await expect(button).toHaveAccessibleName(/\S/)
})

test('视频卡片键盘选择、标签筛选、缩略图时间轴和剪辑区间', async ({ page }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('button', { name: '上传', exact: true })).toBeVisible()
  const sample = execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i',
    'testsrc=size=320x240:rate=25:duration=4', '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
    '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const headers = { 'X-Requested-With': 'ReelVault' }
  const upload = await (await page.request.post('/api/uploads', { headers,
    data: { filename: 'keyboard-video.mp4', size: sample.length, tags: ['键盘标签'] } })).json()
  expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data: sample })).ok()).toBe(true)
  const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
  await page.goto('/library')
  const card = page.locator(`[data-video-id="${video.id}"]`)
  await card.focus()
  await expect(card.getByRole('checkbox', { name: '选择 keyboard-video' })).toBeVisible()
  await page.keyboard.press('Space')
  await expect(card.getByRole('checkbox')).toBeChecked()
  await expect(page.getByRole('status').filter({ hasText: '已选择 1 个' })).toHaveCount(1)
  await page.keyboard.press('Space')
  await expect(card.getByRole('checkbox')).not.toBeChecked()
  const tag = page.getByRole('button', { name: /键盘标签/ })
  await tag.focus()
  await page.keyboard.press('Enter')
  await expect(tag).toHaveAttribute('aria-pressed', 'true')
  await card.focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/videos/${video.id}$`))
  const strip = page.getByRole('slider', { name: '缩略图时间轴' })
  await strip.focus()
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await expect(strip).toHaveAttribute('aria-valuenow', /1(?:\.\d+)?/)
  await page.keyboard.press('Shift+ArrowRight')
  await expect.poll(async () => Number(await strip.getAttribute('aria-valuenow'))).toBeGreaterThan(3.5)
  const start = page.getByRole('slider', { name: '片段 1 起点' })
  await start.focus()
  await page.keyboard.press('ArrowRight')
  expect(Number(await start.getAttribute('aria-valuenow'))).toBeGreaterThan(0)
  for (const button of await page.getByRole('button').all()) await expect(button).toHaveAccessibleName(/\S/)
  await page.screenshot({ path: testInfo.outputPath('keyboard-editor.png'), fullPage: true })
})
