import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('自动年份月份设备和 4K 分类、动态修订、叠加筛选保存及手机长设备名称', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  const ids: string[] = []
  const videos: { id: string; download_url: string }[] = []
  const originals: Buffer[] = []
  for (const [index, size] of ['320x240', '3840x2160', '240x320'].entries()) {
    const tags = index < 2 ? ['-movflags', 'use_metadata_tags+frag_keyframe+empty_moov', '-metadata', 'com.apple.quicktime.creationdate=2024-06-15T12:00:00+08:00', '-metadata', 'com.apple.quicktime.make=AutoTest', '-metadata', 'com.apple.quicktime.model=Camera'] : ['-movflags', 'frag_keyframe+empty_moov']
    const data = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', `color=blue:size=${size}:rate=2:duration=1`, '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p', ...tags, '-f', 'mp4', 'pipe:1'])
    const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: `auto-${index}.mp4`, size: data.length } })).json()
    expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data })).ok()).toBe(true)
    const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
    await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status, { timeout: 60_000 }).toBe('ready')
    ids.push(video.id); videos.push(video); originals.push(data)
  }
  await page.request.patch(`/api/videos/${ids[0]}`, { headers, data: { rating: 5 } })
  await page.goto('/auto-groups')
  await expect(page.getByRole('heading', { name: '自动分组', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '2024 年 · 2 个视频', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '2024-06 · 2 个视频', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'AutoTest Camera · 2 个视频', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '4K 及以上 · 1 个视频', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '4K 及以上 · 1 个视频', exact: true }).click()
  await expect(page.locator('main [data-video-id]')).toHaveCount(1)
  await expect(page.locator(`main [data-video-id="${ids[1]}"]`)).toBeVisible()
  await page.goto('/auto-groups')
  await page.getByRole('link', { name: '2024 年 · 2 个视频', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2024 年', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '全部视频', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('textbox', { name: '搜索视频', exact: true }).fill('auto')
  await page.getByRole('textbox', { name: '搜索视频', exact: true }).press('Enter')
  await expect(page.locator('main [data-video-id]')).toHaveCount(2)
  await page.getByRole('button', { name: '清除搜索与标签筛选', exact: true }).click()
  expect(new URL(page.url()).searchParams.get('auto')).toBe('year:2024')
  await page.goto('/library?auto=year%3A2024&rating_min=4')
  await expect(page.locator('main [data-video-id]')).toHaveCount(1)
  await page.getByRole('button', { name: '保存为智能文件夹', exact: true }).click()
  await page.getByRole('textbox', { name: '智能文件夹名称', exact: true }).fill('自动年份高分')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('heading', { name: '自动年份高分', exact: true })).toBeVisible()
  const saved = (await (await page.request.get('/api/smart-folders')).json()).find((f: { name: string }) => f.name === '自动年份高分')
  expect(saved.filters.auto).toBe('year:2024')
  await page.request.patch(`/api/videos/${ids[0]}/metadata`, { headers, data: { captured_at: null } })
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  await page.request.patch(`/api/videos/${ids[0]}/metadata`, { headers, data: { captured_at: '2024-07-01T00:00:00Z' } })
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toBeVisible()
  await page.goto('/auto-groups')
  await expect(page.getByRole('link', { name: '2024-06 · 1 个视频', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '2024-07 · 1 个视频', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '2024-06 · 1 个视频', exact: true }).click()
  await page.request.patch(`/api/videos/${ids[1]}/metadata`, { headers, data: { captured_at: '2025-01-01T00:00:00Z', device_make: null, device_model: null } })
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '2024-06', exact: true })).toBeVisible()
  const longName = 'Camera_' + 'Z'.repeat(120)
  await page.request.patch(`/api/videos/${ids[0]}/metadata`, { headers, data: { device_model: longName } })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/settings')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.goto('/auto-groups')
  await page.getByRole('textbox', { name: 'Search device categories', exact: true }).fill(longName)
  const deviceLink = page.getByRole('link', { name: `AutoTest ${longName} · 1 video`, exact: true })
  await expect(deviceLink).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('auto-groups-mobile.png'), fullPage: true, animations: 'disabled' })
  await deviceLink.click()
  await expect(page.getByRole('heading', { name: `AutoTest ${longName}`, exact: true })).toBeVisible()
  await expect(page.locator('main [data-video-id]')).toHaveCount(1)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.getByRole('button', { name: 'Remove automatic group condition', exact: true }).click()
  expect(new URL(page.url()).searchParams.has('auto')).toBe(false)
  expect(await (await page.request.get(videos[0].download_url)).body()).toEqual(originals[0])
})

test('无效自动分类显示错误并保留限制', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.goto('/library?auto=resolution%3Aall')
  await expect(page.locator('main')).toContainText('无效的自动分组条件')
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  expect(new URL(page.url()).searchParams.get('auto')).toBe('resolution:all')
})
