import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('真实重复扫描、复核取消、失败保留选择、信息合并恢复及手机英文相似处理', async ({ page }, testInfo) => {
  test.setTimeout(300_000)
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  const sample = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=480x360:rate=17:duration=7', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const smaller = execFileSync('ffmpeg', ['-v', 'error', '-i', 'pipe:0', '-vf', 'scale=240:180', '-c:v', 'libx264', '-crf', '32', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'], { input: sample })
  const ids: string[] = []
  for (const [index, data] of [sample, sample, smaller].entries()) {
    const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: `duplicate-${index}.mp4`, size: data.length } })).json()
    expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data })).ok()).toBe(true)
    const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
    await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
    ids.push(video.id)
  }
  await page.request.patch(`/api/videos/${ids[1]}`, { headers, data: { tags: ['重复汇集'], rating: 5, favorite: true } })
  await page.request.patch(`/api/videos/${ids[1]}/metadata`, { headers, data: { custom_fields: { project: 'retained in library' } } })
  const collection = await (await page.request.post('/api/collections', { headers, data: { name: '重复合集', video_ids: [ids[1]] } })).json()
  await page.goto('/duplicates')
  await expect(page.getByRole('heading', { name: '重复视频检测', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '扫描重复视频', exact: true }).click()
  await expect.poll(async () => (await (await page.request.get('/api/duplicates')).json()).job?.status, { timeout: 240_000 }).toBe('succeeded')
  const exact = page.locator('[data-duplicate-kind="exact"]').filter({ has: page.locator(`[data-duplicate-video-id="${ids[0]}"]`) })
  await expect(exact).toBeVisible()
  await expect(exact.locator('[data-duplicate-video-id]')).toHaveCount(2)
  await expect(exact.locator(`[data-duplicate-video-id="${ids[0]}"]`).getByRole('radio')).toBeChecked()
  await exact.getByRole('button', { name: '处理选中的 1 个视频', exact: true }).click()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  expect((await (await page.request.get(`/api/videos/${ids[1]}`)).json()).deleted_at).toBeNull()
  await page.route('**/api/duplicates/resolve', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: '暂时不可用', code: 'service_unavailable' }) }))
  await exact.getByRole('button', { name: '处理选中的 1 个视频', exact: true }).click()
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(exact.getByRole('alert')).toContainText('暂时不可用')
  await expect(exact.locator(`[data-duplicate-video-id="${ids[0]}"]`).getByRole('radio')).toBeChecked()
  await expect(exact.locator(`[data-duplicate-video-id="${ids[1]}"]`).getByRole('checkbox')).toBeChecked()
  await page.unroute('**/api/duplicates/resolve')
  await exact.getByRole('button', { name: '处理选中的 1 个视频', exact: true }).click()
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(exact).toHaveCount(0)
  const kept = await (await page.request.get(`/api/videos/${ids[0]}`)).json()
  expect(kept.tags).toContain('重复汇集')
  expect(kept.rating).toBe(5)
  expect(kept.favorite).toBe(true)
  expect(kept.metadata.custom_fields.project).toBe('retained in library')
  expect((await (await page.request.get(`/api/collections/${collection.id}`)).json()).items[0].id).toBe(ids[0])
  expect((await (await page.request.get(`/api/videos/${ids[1]}`)).json()).deleted_at).not.toBeNull()
  expect((await page.request.post(`/api/videos/${ids[1]}/restore`, { headers })).ok()).toBe(true)
  await page.reload()
  await expect(exact).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/settings')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.goto('/duplicates?kind=similar')
  const similar = page.locator('[data-duplicate-kind="similar"]').filter({ has: page.locator(`[data-duplicate-video-id="${ids[2]}"]`) })
  await expect(similar).toBeVisible()
  await expect(similar.getByText(/^Visual similarity/)).toBeVisible()
  await similar.locator(`[data-duplicate-video-id="${ids[2]}"]`).getByRole('radio').check()
  await similar.getByRole('checkbox', { name: 'Combine library information into the retained video', exact: true }).uncheck()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('duplicates-mobile.png'), fullPage: true, animations: 'disabled' })
  await similar.getByRole('button', { name: 'Resolve 1 selected videos', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Similar frames do not prove identical content.')
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${ids[0]}`)).json()).deleted_at).not.toBeNull()
  expect((await (await page.request.get(`/api/videos/${ids[2]}`)).json()).rating).toBe(0)
  // The other exact copy becomes the representative; selection must follow current membership.
  await expect(similar.locator(`[data-duplicate-video-id="${ids[1]}"]`)).toBeVisible()
  await expect(similar.locator(`[data-duplicate-video-id="${ids[1]}"]`).getByRole('radio')).toBeChecked()
  await expect(similar.locator(`[data-duplicate-video-id="${ids[2]}"]`).getByRole('checkbox')).toBeChecked()
})
