import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('语言切换保留登录输入、翻译已有错误并在刷新后持久化', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('wrong-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('用户名或密码错误')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await expect(page.getByRole('alert')).toContainText('Incorrect username or password.')
  await expect(page.getByRole('textbox', { name: 'Username', exact: true })).toHaveValue('e2e-admin')
  await expect(page.getByLabel(/^Password/)).toHaveValue('wrong-password')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Username', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^Password/).fill('e2e-secret123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Home', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Continue watching', exact: true })).toBeVisible()
  await page.goto('/settings')
  await page.getByRole('combobox', { name: 'Interface language' }).selectOption('zh')
  await expect(page.getByRole('heading', { name: '设置', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '用户菜单' }).click()
  await page.getByRole('menu').getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
})

test('手机英文上传、编辑草稿切换与离线浏览保留用户标题', async ({ page, context }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/login')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.getByRole('textbox', { name: 'Username', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^Password/).fill('e2e-secret123')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toBeVisible()
  const sample = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=blue:size=320x240:rate=25:duration=3', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: 'Upload videos', exact: true }).click()])
  await chooser.setFiles({ name: '用户影片.mp4', mimeType: 'video/mp4', buffer: sample })
  const completed = page.waitForResponse(response => response.url().endsWith('/complete') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Start upload', exact: true }).click()
  const video = await (await completed).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
  await page.goto(`/videos/${video.id}`)
  await page.getByRole('button', { name: 'Open video editor', exact: true }).click()
  await page.getByRole('tab', { name: 'Trim', exact: true }).click()
  await page.getByRole('textbox', { name: 'New video name (optional)' }).fill('未保存的中文草稿')
  // Drawer keeps focus trapped; update the persisted preference through another tab.
  const settings = await context.newPage()
  await settings.goto('/settings')
  await settings.getByRole('combobox', { name: 'Interface language' }).selectOption('zh')
  await expect(page.getByRole('textbox', { name: '新视频名称（可选）' })).toHaveValue('未保存的中文草稿')
  await settings.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await expect(page.getByRole('textbox', { name: 'New video name (optional)' })).toHaveValue('未保存的中文草稿')
  await settings.close()
  await page.getByRole('button', { name: 'Close video editor', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.locator('[data-media-player]').hover()
  await expect(page.locator('[data-media-player]').getByRole('button', { name: 'Play', exact: true }).first()).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('english-mobile.png'), fullPage: true })
  await page.goto(`/library?q=${encodeURIComponent(video.title)}`)
  await expect(page.locator(`[data-video-id="${video.id}"] img`)).toBeVisible()
  await expect.poll(() => page.evaluate(async () => (await (await caches.open('reelvault-offline-posters')).keys()).length)).toBeGreaterThan(0)
  await context.setOffline(true)
  await page.goto(`/videos/${video.id}`)
  await expect(page.getByRole('heading', { name: 'Offline browsing', exact: true })).toBeVisible()
  await expect(page.locator('figcaption').filter({ hasText: video.title })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Clear offline posters', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('english-offline.png') })
  await context.setOffline(false)
})
