import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('真实拍摄标签读取、失败与语言切换保留草稿、GPS 自定义字段保存和恢复', async ({ page, context }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  const sample = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=blue:size=320x240:rate=25:duration=3', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', 'use_metadata_tags+frag_keyframe+empty_moov', '-metadata', 'com.apple.quicktime.creationdate=2024-06-01T12:30:00+08:00', '-metadata', 'com.apple.quicktime.make=Apple', '-metadata', 'com.apple.quicktime.model=iPhone Test', '-metadata', 'com.apple.quicktime.location.ISO6709=+25.0330+121.5654+15.50/', '-f', 'mp4', 'pipe:1'])
  const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: 'capture-metadata.mp4', size: sample.length } })).json()
  await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data: sample })
  const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
  await page.goto(`/videos/${video.id}`)
  await expect(page.getByText('iPhone Test', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '编辑元数据', exact: true }).click()
  await expect(page.getByLabel('拍摄时间（UTC）')).toHaveValue('2024-06-01T04:30')
  await page.getByLabel('设备型号').fill('保留的中文草稿')
  await page.getByLabel('GPS 纬度').fill('-33.865')
  await page.getByLabel('GPS 经度').fill('151.209')
  await page.getByRole('button', { name: '添加字段', exact: true }).click()
  await page.getByLabel('字段名称 1', { exact: true }).fill('项目')
  await page.getByLabel('字段内容 1', { exact: true }).fill('用户项目')
  const url = `**/api/videos/${video.id}/metadata`
  await context.route(url, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ code: 'request_failed', detail: '请求失败' }) }))
  await page.getByRole('button', { name: '保存元数据', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByLabel('设备型号')).toHaveValue('保留的中文草稿')
  const settings = await context.newPage()
  await settings.goto('/settings')
  await settings.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await expect(page.getByLabel('Device model', { exact: true })).toHaveValue('保留的中文草稿')
  await expect(page.getByLabel('Field value 1', { exact: true })).toHaveValue('用户项目')
  await context.unroute(url)
  await page.getByRole('button', { name: 'Save metadata', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByText('保留的中文草稿', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('用户项目', { exact: true })).toBeVisible()
  const saved = await (await page.request.get(`/api/videos/${video.id}`)).json()
  expect(saved.metadata.gps.latitude).toBe(-33.865)
  expect(saved.metadata.overridden).not.toContain('captured_at')
  expect(saved.captured_at).toBe('2024-06-01T04:30:00+00:00')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('metadata-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Restore media metadata', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByText('iPhone Test', { exact: true })).toBeVisible()
  await expect(page.getByText('用户项目', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Restore media metadata', exact: true })).toBeHidden()
  await settings.close()
})
