import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('audit history records actual login and deletion, preserves failed filters and fits mobile English', async ({ page }, testInfo) => {
  const headers = { 'X-Requested-With': 'ReelVault' }
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('audit-browser-fixture')
  await page.getByLabel(/^密码/).fill('wrong-password-never-audited')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByText('用户名或密码错误', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.goto('/settings')
  const panel = page.locator('#observability')
  await expect(panel.getByRole('heading', { name: '审计与指标', exact: true })).toBeVisible()
  const filter = panel.getByLabel('审计事件', { exact: true })
  await filter.click()
  await page.getByRole('option', { name: '登录失败', exact: true }).click()
  await expect(panel.getByText(/audit-browser-fixture/)).toBeVisible()
  await expect(panel.getByText(/wrong-password-never-audited/)).toHaveCount(0)

  const video = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=160x120:rate=10', '-t', '1', '-c:v', 'libx264', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: 'audit-clip.mp4', size: video.length } })).json()
  expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers: { ...headers, 'Content-Type': 'application/octet-stream' }, data: video })).ok()).toBe(true)
  const imported = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
  expect(imported.id).toBeTruthy()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${imported.id}`)).json()).status).toBe('ready')
  expect((await page.request.delete(`/api/videos/${imported.id}`, { headers })).ok()).toBe(true)
  await page.route('**/api/system/audit?**', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'fixture audit unavailable', code: 'service_unavailable' }) }))
  await filter.click()
  await page.getByRole('option', { name: '视频移入回收站', exact: true }).click()
  await expect(panel.getByRole('alert')).toBeVisible()
  await expect(filter).toHaveValue('视频移入回收站')
  await page.unroute('**/api/system/audit?**')
  await panel.getByRole('button', { name: '刷新审计记录', exact: true }).click()
  await expect(panel.getByText(`对象：${imported.id}`, { exact: true })).toBeVisible()
  await expect(panel.getByText('采集已关闭', { exact: true })).toBeVisible()
  await page.getByLabel('界面语言').selectOption('en')
  await expect(panel.getByRole('heading', { name: 'Audit and metrics', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await panel.scrollIntoViewIfNeeded()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('audit-mobile-english.png'), animations: 'disabled' })
  const apiHistory = await (await page.request.get('/api/system/audit')).json()
  expect(JSON.stringify(apiHistory)).not.toContain('wrong-password-never-audited')
  await page.getByLabel('Interface language').selectOption('zh')
})
