import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('中文标题拼音全拼首字母、原文排序、组合保存、手机英文和标题动态更新', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  const ids: string[] = []
  for (const [index, title] of ['旅行日落 2024', 'lvxingriluo'].entries()) {
    const data = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=blue:size=320x240:rate=12:duration=1', '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
    const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: `pinyin-${index}.mp4`, size: data.length } })).json()
    expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data })).ok()).toBe(true)
    const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
    await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status, { timeout: 60_000 }).toBe('ready')
    await page.request.patch(`/api/videos/${video.id}`, { headers, data: { title, rating: 5, tags: ['拼音海边'] } })
    if (index === 0) await page.request.patch(`/api/videos/${video.id}/metadata`, { headers, data: { captured_at: '2024-06-01T00:00:00Z' } })
    ids.push(video.id)
  }
  const search = page.getByRole('combobox', { name: '搜索视频', exact: true })
  await search.fill('lvxingriluo'); await search.press('Enter')
  await expect(page.locator('main [data-video-id]')).toHaveCount(2)
  await expect(page.locator('main [data-video-id]').first()).toHaveAttribute('data-video-id', ids[1])
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toContainText('标题拼音匹配')
  await search.fill('lǚxíng 日落'); await search.press('Enter')
  await expect(page.locator('main [data-video-id]')).toHaveCount(1)
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toBeVisible()
  await page.goto('/library?auto=year%3A2024')
  await search.fill('LXRL tag:拼音海边 rating:>=4'); await search.press('Enter')
  await expect(page.locator('main [data-video-id]')).toHaveCount(1)
  expect(new URL(page.url()).searchParams.get('auto')).toBe('year:2024')
  await page.getByRole('radio', { name: '列表', exact: true }).press('Space', { timeout: 15_000 })
  await expect(page.locator(`main tr[data-video-id="${ids[0]}"]`)).toContainText('标题拼音匹配')
  await page.getByRole('button', { name: '保存为智能文件夹', exact: true }).click()
  await page.getByRole('textbox', { name: '智能文件夹名称', exact: true }).fill('拼音日落高分')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('heading', { name: '拼音日落高分', exact: true })).toBeVisible()
  await page.request.patch(`/api/videos/${ids[0]}`, { headers, data: { title: '重庆音乐 2024' } })
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/settings')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.goto('/library?q=CQYY')
  await page.getByRole('radio', { name: 'Grid', exact: true }).press('Space', { timeout: 15_000 })
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toContainText('Matched title pinyin')
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toContainText('重庆音乐 2024')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('pinyin-search-mobile.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Search syntax', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('separate syllables and initials')
  await expect(page.getByRole('dialog')).toContainText('unusual names may need their original spelling')
  await page.keyboard.press('Escape')
  const englishSearch = page.getByRole('combobox', { name: 'Search videos', exact: true })
  await englishSearch.fill('chong qing yin yue'); await englishSearch.press('Enter')
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toBeVisible()
  await page.request.patch(`/api/videos/${ids[1]}`, { headers, data: { title: 'CAFÉ旅行' } })
  await englishSearch.fill('café'); await englishSearch.press('Enter')
  await expect(page.locator(`main [data-video-id="${ids[1]}"]`)).toBeVisible()
  await expect(page.locator(`main [data-video-id="${ids[1]}"]`)).not.toContainText('Matched title pinyin')
})
