import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

const headers = { 'X-Requested-With': 'ReelVault' }

test('deferred HEVC cache plays real media, cleans safely, keeps guests read-only and offers HLS', async ({ page, browser }, testInfo) => {
  test.skip(process.env.REELVAULT_PLAYABLE_EAGER_MAX_MB !== '0', 'Run with eager threshold 0 to exercise on-demand media without a 256 MiB fixture.')
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const sample = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x240:rate=10:duration=2', '-c:v', 'libx265', '-preset', 'ultrafast', '-x265-params', 'log-level=error:pools=1', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: 'deferred-hevc.mp4', size: sample.length } })).json()
  expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers: { ...headers, 'Content-Type': 'application/octet-stream' }, data: sample })).ok()).toBe(true)
  const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
  const endpoint = `/api/videos/${video.id}/playback-cache`
  expect((await (await page.request.get(endpoint)).json()).cached).toBe(false)
  await page.goto(`/videos/${video.id}`)
  await expect(page.getByText('此视频需要兼容播放缓存或 HLS，准备好后即可播放。', { exact: true })).toBeVisible()
  await page.route('**/playback-cache', async route => {
    if (route.request().method() === 'POST') return route.fulfill({ status: 507, json: { code: 'storage_budget_exceeded', detail: '磁盘可用空间不足，请清理空间或取消未完成任务后重试', params: {} } })
    return route.continue()
  })
  await page.getByRole('button', { name: '生成兼容播放缓存', exact: true }).click()
  await expect(page.getByText(/磁盘可用空间不足/)).toBeVisible()
  await page.unroute('**/playback-cache')
  await page.getByRole('button', { name: '生成兼容播放缓存', exact: true }).click()
  await expect(page.getByText(/^兼容播放缓存已就绪/)).toBeVisible()
  await expect.poll(() => page.locator('video').evaluate((el: HTMLVideoElement) => el.readyState)).toBeGreaterThanOrEqual(2)
  await page.locator('video').evaluate((el: HTMLVideoElement) => el.play())
  await expect.poll(() => page.locator('video').evaluate((el: HTMLVideoElement) => el.currentTime)).toBeGreaterThan(0.1)
  const share = await (await page.request.post('/api/shares', { headers, data: { video_id: video.id } })).json()
  expect(share.url).toBeTruthy()
  const context = await browser.newContext()
  const visitor = await context.newPage()
  try {
    await visitor.goto(share.url)
    await expect.poll(() => visitor.locator('video').evaluate((el: HTMLVideoElement) => el.readyState)).toBeGreaterThanOrEqual(2)
    expect((await visitor.request.post(endpoint, { headers })).status()).toBe(401)
    await page.getByRole('button', { name: '清理兼容播放缓存', exact: true }).click()
    await expect(page.getByRole('button', { name: '生成兼容播放缓存', exact: true })).toBeVisible()
    await expect(visitor.getByText('播放缓存尚未就绪，请联系分享者生成兼容播放缓存。', { exact: true })).toBeVisible()
    expect(await (await page.request.get(`/api/videos/${video.id}/download`)).body()).toEqual(sample)
    await page.getByRole('button', { name: '用户菜单', exact: true }).click()
    await page.getByRole('menu').getByLabel('界面语言').selectOption('en')
    await page.keyboard.press('Escape')
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.getByRole('button', { name: 'Generate compatible playback cache', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Generate compatible playback cache', exact: true }).scrollIntoViewIfNeeded()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('playback-cache-mobile-english.png'), animations: 'disabled' })
    await page.getByRole('button', { name: 'Generate compatible playback cache', exact: true }).click()
    await expect(page.getByText(/^Compatible playback cache is ready/)).toBeVisible()
    await expect.poll(() => visitor.locator('video').evaluate((el: HTMLVideoElement) => el.readyState)).toBeGreaterThanOrEqual(2)
    await page.getByRole('button', { name: 'Clear playback cache', exact: true }).click()
    expect((await page.request.put('/api/system/hls', { headers, data: { enabled: true, min_size_mb: 0, max_cache_gb: 20 } })).ok()).toBe(true)
    await page.reload()
    await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}/hls`)).json()).package).toBeTruthy()
    await expect.poll(() => page.locator('video').evaluate((el: HTMLVideoElement) => el.readyState)).toBeGreaterThanOrEqual(2)
    expect((await (await page.request.get(endpoint)).json()).cached).toBe(false)
  } finally {
    await context.close()
    await page.request.put('/api/system/hls', { headers, data: { enabled: false, min_size_mb: 256, max_cache_gb: 20 } })
  }
})
