import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('组合搜索语法、引号标签、保存规则、错误提示与手机英文说明', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  const ids: string[] = []
  for (const [index, duration] of [2, 1, 2].entries()) {
    const data = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', `color=blue:size=320x240:rate=12:duration=${duration}`, '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
    const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: `syntax-2024-${index}.mp4`, size: data.length } })).json()
    expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data })).ok()).toBe(true)
    const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
    await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status, { timeout: 60_000 }).toBe('ready')
    expect((await page.request.patch(`/api/videos/${video.id}`, { headers, data: { tags: ['语法旅行', '家庭 旅行'], rating: index === 2 ? 3 : 5 } })).ok()).toBe(true)
    ids.push(video.id)
  }
  const query = 'tag:语法旅行 rating:>=4 duration:>1s 2024'
  const search = page.getByRole('combobox', { name: '搜索视频', exact: true })
  await search.fill(query); await search.press('Enter')
  await expect(page.locator('main [data-video-id]')).toHaveCount(1)
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toBeVisible()
  await expect(page.locator('main mark').first()).toHaveText('2024')
  expect(new URL(page.url()).searchParams.get('q')).toBe(query)
  await page.getByRole('button', { name: '保存为智能文件夹', exact: true }).click()
  await page.getByRole('textbox', { name: '智能文件夹名称', exact: true }).fill('语法旅行高分')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('heading', { name: '语法旅行高分', exact: true })).toBeVisible()
  await page.request.patch(`/api/videos/${ids[0]}`, { headers, data: { rating: 2 } })
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  await page.goto('/library')
  await search.fill('tag:"家庭 旅行" tag:语法旅行 duration:>=2s')
  await search.press('Enter')
  await expect(page.locator('main [data-video-id]')).toHaveCount(2)
  await search.fill('rating:6'); await search.press('Enter')
  await expect(page.locator('main')).toContainText('搜索条件无效：rating:6')
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/settings')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.getByRole('button', { name: 'Search syntax', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('tag:Travel rating:>=4 duration:>10m 2024')
  await expect(page.getByRole('dialog')).toContainText('2024 is a keyword')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('search-syntax-mobile.png'), animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goto('/library?q=duration%3Axyz')
  await expect(page.locator('main')).toContainText('Invalid search condition: duration:xyz')
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
})
