import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('分组建议、拼音选择、键盘历史、删除失败保留、刷新重登及手机英文', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  expect((await page.request.delete('/api/search/recent', { headers })).ok()).toBe(true)
  const data = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=blue:size=320x240:rate=12:duration=1', '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: 'suggestion.mp4', size: data.length } })).json()
  await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data })
  const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status, { timeout: 60_000 }).toBe('ready')
  await page.request.patch(`/api/videos/${video.id}`, { headers, data: { title: '联想旅行日落', tags: ['联想旅行'] } })
  const folder = await (await page.request.post('/api/folders', { headers, data: { name: '联想旅行目录' } })).json()
  const search = page.getByRole('combobox', { name: '搜索视频', exact: true })
  const initialURL = page.url()
  await search.click()
  await search.dispatchEvent('compositionstart')
  await search.fill('联想')
  await search.press('Enter')
  expect(page.url()).toBe(initialURL)
  await expect(search).toHaveAttribute('aria-expanded', 'false')
  await search.dispatchEvent('compositionend')
  await search.fill('联想')
  await expect(page.getByRole('option', { name: '联想旅行日落', exact: true })).toBeVisible()
  await expect(page.getByRole('option', { name: '联想旅行', exact: true })).toBeVisible()
  await expect(page.getByRole('option', { name: '联想旅行目录', exact: true })).toBeVisible()
  let releaseOld!: () => void
  let oldStarted!: () => void
  const oldRequest = new Promise<void>(resolve => { oldStarted = resolve })
  const oldResponse = new Promise<void>(resolve => { releaseOld = resolve })
  await page.route('**/api/search/suggestions?q=*', async route => {
    if (new URL(route.request().url()).searchParams.get('q') !== '旧建议') return route.continue()
    oldStarted()
    await oldResponse
    await route.fulfill({ json: { videos: [{ id: video.id, name: '旧请求结果' }], tags: [], folders: [] } })
  })
  await search.fill('旧建议')
  await oldRequest
  await search.fill('联想')
  await expect(page.getByRole('option', { name: '联想旅行日落', exact: true })).toBeVisible()
  releaseOld()
  await page.unrouteAll({ behavior: 'wait' })
  await expect(page.getByRole('option', { name: '旧请求结果', exact: true })).toHaveCount(0)
  expect(await (await page.request.get('/api/search/recent')).json()).toEqual([])
  await page.getByRole('option', { name: '联想旅行', exact: true }).click()
  expect(new URL(page.url()).searchParams.get('tag')).toBe('联想旅行')
  await expect(page.locator(`main [data-video-id="${video.id}"]`)).toBeVisible()
  await expect(search).toHaveValue('')
  await search.fill('联想')
  await page.getByRole('option', { name: '联想旅行目录', exact: true }).click()
  expect(new URL(page.url()).searchParams.get('folder')).toBe(String(folder.id))
  await expect(search).toHaveValue('')
  await search.fill('lxlxrl')
  await expect(page.getByRole('option', { name: '联想旅行日落', exact: true })).toBeVisible()
  await search.press('ArrowDown'); await search.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/videos/${video.id}$`))
  await page.goto('/library')
  await search.fill('联想旅行 rating:>=0'); await search.press('Enter')
  await expect(page.locator(`main [data-video-id="${video.id}"]`)).toBeVisible()
  await expect.poll(async () => (await (await page.request.get('/api/search/recent')).json())[0]?.query).toBe('联想旅行 rating:>=0')
  await page.reload()
  await search.fill(''); await search.click()
  await expect(page.getByRole('option', { name: '联想旅行 rating:>=0', exact: true })).toBeVisible()
  await search.press('ArrowDown'); await search.press('Enter')
  expect(new URL(page.url()).searchParams.get('q')).toBe('联想旅行 rating:>=0')
  await page.getByRole('button', { name: '管理最近搜索', exact: true }).click()
  await page.route('**/api/search/recent/*', route => route.request().method() === 'DELETE' ? route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ code: 'conflict', detail: '删除失败' }) }) : route.continue())
  await page.getByRole('button', { name: '删除最近搜索「联想旅行 rating:>=0」', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('删除失败')
  await expect(page.getByRole('button', { name: '删除最近搜索「联想旅行 rating:>=0」', exact: true })).toBeVisible()
  await page.unroute('**/api/search/recent/*')
  await page.keyboard.press('Escape')
  await page.request.post('/api/auth/logout', { headers })
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/settings')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.goto('/library')
  const english = page.getByRole('combobox', { name: 'Search videos', exact: true })
  await english.click()
  await expect(page.getByRole('option', { name: '联想旅行 rating:>=0', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('search-suggestions-mobile.png'), animations: 'disabled' })
  await english.press('ArrowDown'); await english.press('Delete')
  await expect(page.getByRole('option', { name: '联想旅行 rating:>=0', exact: true })).toHaveCount(0)
  expect(await (await page.request.get('/api/search/recent')).json()).toEqual([])
})
