import { execFileSync } from 'node:child_process'
import { expect, test, type Page } from '@playwright/test'

const headers = { 'X-Requested-With': 'ReelVault' }

async function seedVideo(page: Page, name: string) {
  const sample = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=green:size=320x240:rate=25:duration=2', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: name + '.mp4', size: sample.length } })).json()
  expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers: { ...headers, 'Content-Type': 'application/octet-stream' }, data: sample })).ok()).toBe(true)
  const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
  return video
}

test('password shares are read-only, play actual media, gate downloads and revoke live visitors', async ({ page, browser }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const video = await seedVideo(page, 'shared-private')
  await page.goto(`/videos/${video.id}`)
  await page.getByRole('button', { name: '分享', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '分享链接' })
  await dialog.getByLabel('有效期（小时）', { exact: true }).fill('24')
  await dialog.getByLabel('访问密码（可选，至少 6 个字符）', { exact: true }).fill('visitor-secret')
  // A failed request must preserve the draft and permit retry.
  await page.route('**/api/shares', async route => {
    if (route.request().method() === 'POST') return route.fulfill({ status: 500, json: { code: 'internal_error', detail: '服务器无法完成请求' } })
    await route.continue()
  })
  await dialog.getByRole('button', { name: '生成分享链接' }).click()
  await expect(dialog.getByText('服务器无法完成请求')).toBeVisible()
  await expect(dialog.getByLabel('访问密码（可选，至少 6 个字符）', { exact: true })).toHaveValue('visitor-secret')
  await page.unroute('**/api/shares')
  await dialog.getByRole('button', { name: '生成分享链接' }).click()
  await expect(dialog.getByLabel('分享地址', { exact: true })).toBeVisible()
  const shareURL = await dialog.getByLabel('分享地址', { exact: true }).inputValue()
  await page.setViewportSize({ width: 390, height: 844 })
  await dialog.getByLabel('分享地址', { exact: true }).scrollIntoViewIfNeeded()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('share-owner-mobile.png'), animations: 'disabled' })
  const visitorContext = await browser.newContext()
  const visitor = await visitorContext.newPage()
  try {
    const navigation = await visitor.goto(shareURL)
    expect(navigation?.headers()["cache-control"]).toBe("no-store")
    expect(navigation?.headers()["referrer-policy"]).toBe("no-referrer")
    await expect(visitor.getByLabel('分享访问密码', { exact: true })).toBeVisible()
    await expect(visitor.getByText('shared-private')).toHaveCount(0)
    await visitor.getByLabel('分享访问密码', { exact: true }).fill('wrong')
    await visitor.getByRole('button', { name: '打开分享' }).click()
    await expect(visitor.getByText('分享访问密码不正确')).toBeVisible()
    await visitor.getByLabel('分享访问密码', { exact: true }).fill('visitor-secret')
    await visitor.getByRole('button', { name: '打开分享' }).click()
    await expect(visitor.getByRole('heading', { name: 'shared-private', exact: true })).toBeVisible()
    await expect(visitor.getByRole('link', { name: '下载原文件' })).toHaveCount(0)
    await expect(visitor.getByRole('button', { name: '上传', exact: true })).toHaveCount(0)
    expect((await visitor.request.get('/api/videos')).status()).toBe(401)
    await expect.poll(() => visitor.locator('video').evaluate((element: HTMLVideoElement) => element.readyState)).toBeGreaterThanOrEqual(2)
    await visitor.locator('video').evaluate((element: HTMLVideoElement) => element.play())
    await expect.poll(() => visitor.locator('video').evaluate((element: HTMLVideoElement) => element.currentTime)).toBeGreaterThan(0)
    await visitor.reload()
    await expect(visitor.getByRole('heading', { name: 'shared-private', exact: true })).toBeVisible()
    await expect.poll(() => visitor.locator('video').evaluate((element: HTMLVideoElement) => element.readyState)).toBeGreaterThanOrEqual(2)
    await visitor.setViewportSize({ width: 390, height: 844 })
    await visitor.getByRole('combobox', { name: '界面语言' }).selectOption('en')
    await expect(visitor.getByText(/Read-only access/)).toBeVisible()
    await expect.poll(() => visitor.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await visitor.screenshot({ path: testInfo.outputPath('share-visitor-mobile.png'), animations: 'disabled' })
    const cached = await visitor.evaluate(async () => {
      const urls = []
      for (const name of await caches.keys()) for (const request of await (await caches.open(name)).keys()) urls.push(request.url)
      return urls.filter(url => url.includes('/api/public/shares/') || url.includes('/share/'))
    })
    expect(cached).toEqual([])
    await dialog.getByRole('button', { name: '撤销分享' }).click()
    await expect(visitor.getByText('This share is unavailable, revoked or expired.')).toBeVisible({ timeout: 15000 })
    await expect(visitor.locator('video')).toHaveCount(0)
  } finally { await visitorContext.close() }
})

test('collection sharing follows membership changes and can download only when enabled', async ({ page, browser }) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const video = await seedVideo(page, 'share-collection-first')
  const next = await seedVideo(page, 'share-collection-second')
  const collection = await (await page.request.post('/api/collections', { headers, data: { name: `分享合集-${Date.now()}`, video_ids: [video.id, next.id] } })).json()
  await page.goto(`/collections/${collection.id}`)
  await page.getByRole('button', { name: '分享', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '分享链接' })
  await dialog.getByRole('switch', { name: '允许下载原文件', exact: true }).check()
  await dialog.getByRole('button', { name: '生成分享链接' }).click()
  await expect(dialog.getByLabel('分享地址', { exact: true })).toBeVisible()
  const url = await dialog.getByLabel('分享地址', { exact: true }).inputValue()
  const guest = await browser.newContext()
  try {
    const visitor = await guest.newPage()
    await visitor.goto(url)
    await expect(visitor.getByRole('heading', { name: collection.name, exact: true })).toBeVisible()
    const download = visitor.getByRole('link', { name: '下载原文件', exact: true })
    await expect(download).toBeVisible()
    expect((await visitor.request.get((await download.getAttribute('href'))!)).ok()).toBe(true)
    await visitor.locator('video').evaluate(async (element: HTMLVideoElement) => { element.currentTime = 1.8; await element.play() })
    await expect(visitor.locator('video')).toHaveAttribute('src', new RegExp(next.id))
    await expect.poll(() => visitor.locator('video').evaluate((element: HTMLVideoElement) => element.currentTime)).toBeGreaterThan(0)
    expect((await page.request.delete(`/api/collections/${collection.id}/items/${video.id}`, { headers })).ok()).toBe(true)
    expect((await page.request.delete(`/api/collections/${collection.id}/items/${next.id}`, { headers })).ok()).toBe(true)
    await expect(visitor.getByText('分享中暂无可播放的视频')).toBeVisible()
    await expect(visitor.locator('video')).toHaveCount(0)
  } finally { await guest.close() }
})
