import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

test('保存筛选动态匹配、预览与冲突重试、排序刷新及手机管理保留视频', async ({ page }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const headers = { 'X-Requested-With': 'ReelVault' }
  const sample = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=blue:size=320x240:rate=25:duration=3', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const ids: string[] = []
  for (const rating of [4, 3]) {
    const upload = await (await page.request.post('/api/uploads', { headers, data: { filename: `smart-${rating}.mp4`, size: sample.length } })).json()
    expect((await page.request.put(`/api/uploads/${upload.id}?offset=0`, { headers, data: sample })).ok()).toBe(true)
    const video = await (await page.request.post(`/api/uploads/${upload.id}/complete`, { headers })).json()
    await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
    await page.request.patch(`/api/videos/${video.id}`, { headers, data: { rating, tags: ['智能旅行'] } })
    ids.push(video.id)
  }
  await page.goto('/library?rating_min=4&duration_min=2&tag=智能旅行&sort=title&order=asc&page=2')
  // Saved searches start from page one even when created on another page.
  await page.getByRole('button', { name: '保存为智能文件夹', exact: true }).click()
  await page.getByRole('textbox', { name: '智能文件夹名称' }).fill('高分旅行')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('heading', { name: '高分旅行', exact: true })).toBeVisible()
  await expect(page.locator('main [data-video-id]')).toHaveCount(1)
  await expect(page.locator(`main [data-video-id="${ids[0]}"]`)).toBeVisible()
  const folder = (await (await page.request.get('/api/smart-folders')).json()).find((item: { name: string }) => item.name === '高分旅行')
  expect(folder.filters.sort).toBe('title')
  expect(folder.filters.order).toBe('asc')
  expect(folder.filters.page).toBeUndefined()
  await page.request.patch(`/api/videos/${ids[0]}`, { headers, data: { rating: 2 } })
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  await page.request.patch(`/api/videos/${ids[1]}`, { headers, data: { rating: 5 } })
  await expect(page.locator(`main [data-video-id="${ids[1]}"]`)).toBeVisible()
  await page.getByRole('textbox', { name: '最短时长（秒）', exact: true }).fill('10')
  await expect(page.getByText('筛选条件已修改，尚未保存到智能文件夹。')).toBeVisible()
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
  expect((await (await page.request.get('/api/smart-folders')).json()).find((item: { id: number }) => item.id === folder.id).filters.duration_min).toBe(2)
  await page.request.post('/api/smart-folders', { headers, data: { name: '已占用', filters: {} } })
  await page.getByRole('button', { name: '更新智能文件夹', exact: true }).click()
  await page.getByRole('textbox', { name: '智能文件夹名称' }).fill('已占用')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('同名智能文件夹已存在')
  await expect(page.getByRole('textbox', { name: '智能文件夹名称' })).toHaveValue('已占用')
  await page.getByRole('textbox', { name: '智能文件夹名称' }).fill('长旅行')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('heading', { name: '长旅行', exact: true })).toBeVisible()
  await expect(page.getByText('智能文件夹自动显示当前匹配的视频。')).toBeVisible()
  await page.getByRole('link', { name: '长旅行', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '最短时长（秒）', exact: true })).toHaveValue('10')
  await page.reload()
  await expect(page.getByRole('textbox', { name: '最短时长（秒）', exact: true })).toHaveValue('10')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/settings')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.goto(`/library?smart=${folder.id}`)
  await expect(page.getByRole('heading', { name: '长旅行', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save as smart folder', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('smart-folder-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Open navigation menu', exact: true }).click()
  await page.getByRole('button', { name: 'Smart folder menu for 长旅行', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page).toHaveURL(/\/library$/)
  expect((await (await page.request.get(`/api/videos/${ids[1]}`)).json()).deleted_at).toBeNull()
})

test('不存在的智能文件夹不退回全部视频', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  const requests: string[] = []
  page.on('request', request => { if (new URL(request.url()).pathname === '/api/videos') requests.push(request.url()) })
  await page.goto('/library?smart=999999')
  await expect(page.getByRole('alert')).toContainText('智能文件夹不存在或已删除。')
  expect(requests).toHaveLength(0)
  await expect(page.locator('main [data-video-id]')).toHaveCount(0)
})
