import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

const headers = { 'X-Requested-With': 'ReelVault' }

test('空间阈值持久化、上传前预估与编辑不足保留参数，以及手机英文预警', async ({ page, context }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.goto('/settings')
  await page.getByLabel('剩余空间预警（MiB）', { exact: true }).fill('1048576')
  await page.getByLabel('剩余空间预警（%）', { exact: true }).fill('0')
  await page.getByRole('button', { name: '保存空间预警设置' }).click()
  await expect(page.getByText(/扣除未完成任务后可用 .*低于预警阈值/)).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('剩余空间预警（MiB）', { exact: true })).toHaveValue('1048576')
  const sample = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=green:size=320x240:rate=25:duration=2', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: '上传', exact: true }).click()])
  await chooser.setFiles({ name: 'storage-review.mp4', mimeType: 'video/mp4', buffer: sample })
  const review = page.getByRole('dialog', { name: '上传设置' })
  await expect(review.getByText(/预计需要 .*实际占用取决于/)).toBeVisible()
  await expect(review.getByRole('button', { name: '开始上传' })).toBeEnabled()
  const completed = page.waitForResponse(r => r.url().endsWith('/complete') && r.request().method() === 'POST')
  await review.getByRole('button', { name: '开始上传' }).click()
  const video = await (await completed).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
  const estimate = await (await page.request.post('/api/system/storage/estimate', { headers, data: { upload_sizes: [sample.length] } })).json()
  await context.route('**/api/system/storage/estimate', route => route.fulfill({ json: { ...estimate, sufficient: false, available_bytes: 0 } }))
  const [blockedChooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: '上传', exact: true }).click()])
  await blockedChooser.setFiles({ name: 'blocked.mp4', mimeType: 'video/mp4', buffer: sample })
  await expect(review.getByRole('button', { name: '开始上传' })).toBeDisabled()
  await expect(review.getByText('磁盘可用空间不足，请清理空间或取消未完成任务后重试')).toBeVisible()
  await review.getByRole('button', { name: '取消', exact: true }).click()
  await page.goto(`/videos/${video.id}`)
  await page.getByRole('tab', { name: '旋转', exact: true }).click()
  const panel = page.getByRole('tabpanel').filter({ has: page.getByRole('button', { name: '应用旋转' }) })
  await panel.getByRole('textbox', { name: '新视频名称（可选）' }).fill('retain-on-insufficient')
  let submitted = 0
  page.on('request', r => { if (r.url().endsWith(`/videos/${video.id}/edit`)) submitted++ })
  await panel.getByRole('button', { name: '应用旋转' }).click()
  await expect(page.getByText('磁盘可用空间不足，请清理空间或取消未完成任务后重试')).toBeVisible()
  await expect(panel.getByRole('textbox', { name: '新视频名称（可选）' })).toHaveValue('retain-on-insufficient')
  expect(submitted).toBe(0)
  await context.unroute('**/api/system/storage/estimate')
  await panel.getByRole('button', { name: '应用旋转' }).click()
  await expect(page.getByText('任务已提交', { exact: true })).toBeVisible()
  await page.goto('/settings')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await expect(page.getByText(/Available after unfinished tasks: .*below the warning threshold/)).toBeVisible()
  await expect(page.getByLabel('Free space warning (MiB)', { exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.getByLabel('Free space warning (MiB)', { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('storage-mobile.png'), animations: 'disabled' })
  // Restore shared fixture preferences for subsequent tests.
  expect((await page.request.put('/api/system/storage', { headers, data: { warning_mb: 1024, warning_percent: 5 } })).ok()).toBe(true)
})
