import { expect, test } from '@playwright/test'

test('标签管理保留失败输入，整理颜色分组并合并删除，手机英文页面无溢出', async ({ page }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '标签管理', exact: true }).click()
  await page.getByRole('button', { name: '新建标签分组', exact: true }).click()
  await page.getByRole('textbox', { name: '分组名称' }).fill('人物测试')
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(page.getByText('人物测试 · 0 个标签')).toBeVisible()
  const create = async (name: string) => {
    await page.getByRole('button', { name: '新建标签', exact: true }).click()
    await page.getByRole('textbox', { name: '标签名称' }).fill(name)
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByRole('button', { name: `编辑标签 ${name}`, exact: true })).toBeVisible()
  }
  await create('来源标签')
  await create('目标标签')
  await page.getByRole('button', { name: '编辑标签 来源标签', exact: true }).click()
  await page.getByRole('textbox', { name: '标签名称' }).fill('目标标签')
  await page.getByRole('textbox', { name: '标签颜色' }).fill('#119955')
  await page.getByRole('textbox', { name: '标签颜色' }).press('Tab')
  await page.getByRole('combobox', { name: '标签分组', exact: true }).click()
  await page.getByRole('option', { name: '人物测试', exact: true }).click()
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByRole('textbox', { name: '标签名称' })).toHaveValue('目标标签')
  await expect(page.getByRole('textbox', { name: '标签颜色' })).toHaveValue('#119955')
  await page.getByRole('textbox', { name: '标签名称' }).fill('人物甲')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByText('人物测试 · 1 个标签')).toBeVisible()
  await page.getByRole('combobox', { name: '按标签分组筛选' }).click()
  await page.getByRole('option', { name: '人物测试', exact: true }).click()
  await expect(page.getByRole('button', { name: '编辑标签 人物甲', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '编辑标签 目标标签', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '合并标签 人物甲', exact: true }).click()
  await page.getByRole('combobox', { name: '合并到标签' }).click()
  await page.getByRole('option', { name: '目标标签', exact: true }).click()
  await page.getByRole('button', { name: '合并标签', exact: true }).click()
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('button', { name: '编辑标签 人物甲', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '删除分组 人物测试', exact: true }).click()
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(page.getByRole('button', { name: '编辑标签 目标标签', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '编辑标签 目标标签', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/settings')
  await page.getByRole('combobox', { name: '界面语言' }).selectOption('en')
  await page.goto('/tags')
  await expect(page.getByRole('heading', { name: 'Tag management', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('tags-mobile-english.png'), fullPage: true })
  await page.getByRole('button', { name: 'Delete tag 目标标签', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit tag 目标标签', exact: true })).toBeHidden()
})
