import { createHmac } from 'node:crypto'
import { expect, test } from '@playwright/test'

function code(secret: string) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
  const bits = [...secret].map(char => alphabet.indexOf(char).toString(2).padStart(5, '0')).join('')
  const key = Buffer.from(bits.match(/.{8}/g)!.map(byte => parseInt(byte, 2)))
  const counter = Buffer.alloc(8)
  counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000)))
  const digest = createHmac('sha1', key).update(counter).digest()
  return ((digest.readUInt32BE(digest[19] & 15) & 0x7fffffff) % 1000000).toString().padStart(6, '0')
}

test('authenticator setup, recovery download, login challenge and disable work on mobile', async ({ page }, testInfo) => {
  const headers = { 'X-Requested-With': 'ReelVault' }
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.goto('/settings')
  const panel = page.getByRole('heading', { name: '两步验证', exact: true }).locator('..')
  await panel.getByLabel('当前密码', { exact: true }).fill('e2e-secret123')
  const enrollmentResponse = page.waitForResponse(response => response.url().endsWith('/api/auth/totp/enroll'))
  await panel.getByRole('button', { name: '设置验证器', exact: true }).click()
  const enrollment = await (await enrollmentResponse).json()
  await expect(panel.getByAltText('验证器设置二维码')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await panel.scrollIntoViewIfNeeded()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('totp-enrollment-mobile.png'), animations: 'disabled' })
  await panel.getByLabel('验证码或恢复码', { exact: true }).fill(code(enrollment.secret))
  await panel.getByRole('button', { name: '确认启用', exact: true }).click()
  const codesField = panel.getByLabel('恢复码', { exact: true })
  await expect(codesField).toBeVisible()
  const codes = (await codesField.inputValue()).split('\n')
  expect(codes).toHaveLength(10)
  const downloaded = page.waitForEvent('download')
  await panel.getByRole('button', { name: '下载恢复码', exact: true }).click()
  expect((await downloaded).suggestedFilename()).toBe('reelvault-recovery-codes.txt')
  await panel.getByRole('button', { name: '已安全保存', exact: true }).click()
  await expect(codesField).toHaveCount(0)
  await page.request.post('/api/auth/logout', { headers })
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '验证码或恢复码', exact: true })).toBeVisible()
  await expect(page.getByLabel(/^密码/)).toHaveValue('e2e-secret123')
  await page.getByRole('textbox', { name: '验证码或恢复码', exact: true }).fill('00000000')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByText('验证码无效或已使用', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '验证码或恢复码', exact: true }).fill(codes[0])
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.goto('/settings')
  await expect(panel.getByText('已启用验证器，剩余 9 个恢复码')).toBeVisible()
  await panel.getByLabel('当前密码', { exact: true }).fill('e2e-secret123')
  await panel.getByLabel('验证码或恢复码', { exact: true }).fill(codes[1])
  await panel.getByRole('button', { name: '关闭两步验证', exact: true }).click()
  await expect(panel.getByRole('button', { name: '设置验证器', exact: true })).toBeVisible()
})
