import { execFileSync } from 'node:child_process'
import { expect, test } from '@playwright/test'

const headers = { 'X-Requested-With': 'ReelVault' }
async function login(page: import('@playwright/test').Page) {
  await page.goto('/login')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('e2e-admin')
  await page.getByLabel(/^密码/).fill('e2e-secret123')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
}

test('画面搜索默认关闭且中英文手机布局可用', async ({ page }, testInfo) => {
  await login(page)
  await page.goto('/visual-search')
  await expect(page.getByRole('heading', { name: '画面搜索', exact: true })).toBeVisible()
  await expect(page.getByText('管理员尚未启用画面搜索。', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '搜索', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '用户菜单', exact: true }).click()
  await page.getByRole('menu').getByLabel('界面语言').selectOption('en')
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: 'Visual search', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('visual-search-disabled-mobile.png'), animations: 'disabled' })
})

test('真实 CLIP 索引、文字与图片搜索、时间跳转和手机英文布局', async ({ page }, testInfo) => {
  test.skip(!process.env.REELVAULT_TEST_VISION_URL, 'requires a prepared private CLIP service')
  await login(page)
  const source = execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc=size=320x240:rate=15:duration=4', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', 'frag_keyframe+empty_moov', '-f', 'mp4', 'pipe:1'])
  const incoming = await (await page.request.post('/api/uploads', { headers, data: { filename: '真实画面搜索.mp4', size: source.length } })).json()
  expect((await page.request.put(`/api/uploads/${incoming.id}?offset=0`, { headers, data: source })).ok()).toBe(true)
  const video = await (await page.request.post(`/api/uploads/${incoming.id}/complete`, { headers })).json()
  await expect.poll(async () => (await (await page.request.get(`/api/videos/${video.id}`)).json()).status).toBe('ready')
  await page.goto(`/videos/${video.id}`)
  await page.getByLabel('抽帧间隔（秒）', { exact: true }).fill('1')
  await page.getByRole('button', { name: '生成画面索引', exact: true }).click()
  await expect(page.getByText('已索引 4 个画面', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '搜索此视频的画面', exact: true }).click()
  await page.getByRole('textbox', { name: '描述要查找的画面', exact: true }).fill('彩色的测试图案')
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(page.getByText('按相似度排序的 4 个结果', { exact: true })).toBeVisible()
  const result = await (await page.request.get(`/api/visual-search?q=${encodeURIComponent('彩色的测试图案')}&video_id=${video.id}`)).json()
  const image = await (await page.request.get(result.items[0].thumbnail)).body()
  await page.getByText('上传图片', { exact: true }).click()
  await page.locator('input[type=file][accept="image/png,image/jpeg,image/webp"]').setInputFiles({ name: 'query.jpg', mimeType: 'image/jpeg', buffer: image })
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(page.getByText('按相似度排序的 4 个结果', { exact: true })).toBeVisible()
  await page.locator(`a[href="/videos/${video.id}?t=1.000000"]`).first().click()
  const time = Number(new URL(page.url()).searchParams.get('t'))
  expect(time).toBe(1)
  await expect.poll(() => page.locator('video').evaluate((el: HTMLVideoElement) => el.currentTime)).toBeCloseTo(time, 1)
  await page.getByRole('link', { name: '搜索此视频的画面', exact: true }).click()
  await page.getByRole('textbox', { name: '描述要查找的画面', exact: true }).fill('彩色的测试图案')
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(page.getByText('按相似度排序的 4 个结果', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '用户菜单', exact: true }).click()
  await page.getByRole('menu').getByLabel('界面语言').selectOption('en')
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: 'Visual search', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('visual-search-mobile-english.png'), animations: 'disabled' })
  expect(await (await page.request.get(`/api/videos/${video.id}/download`)).body()).toEqual(source)
})
