"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 13:47:02.751920
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelvault.models

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["folders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("folders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_folders_parent_id"), ["parent_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("video_ids", sa.JSON(), nullable=False),
        sa.Column("result_video_id", sa.String(length=32), nullable=True),
        sa.Column("result_file", sa.String(length=512), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.Column("started_at", reelvault.models.UTCDateTime(), nullable=True),
        sa.Column("finished_at", reelvault.models.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("received", sa.Integer(), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.Column("created_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.Column("password_changed_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prev_token_hash", sa.String(length=64), nullable=True),
        sa.Column("device_name", sa.String(length=128), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("remember", sa.Boolean(), nullable=False),
        sa.Column("created_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.Column("expires_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.Column("rotated_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_prev_token_hash"), ["prev_token_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("playable_path", sa.String(length=512), nullable=True),
        sa.Column("source_path", sa.String(length=1024), nullable=True),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("bitrate", sa.Integer(), nullable=False),
        sa.Column("container", sa.String(length=64), nullable=False),
        sa.Column("video_codec", sa.String(length=32), nullable=False),
        sa.Column("audio_codec", sa.String(length=32), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("has_poster", sa.Boolean(), nullable=False),
        sa.Column("has_preview", sa.Boolean(), nullable=False),
        sa.Column("has_sprite", sa.Boolean(), nullable=False),
        sa.Column("asset_version", sa.Integer(), nullable=False),
        sa.Column("cover_time", sa.Float(), nullable=True),
        sa.Column("created_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", reelvault.models.UTCDateTime(), nullable=False),
        sa.Column("deleted_at", reelvault.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_videos_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_folder_id"), ["folder_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_source_path"), ["source_path"], unique=False)

    op.create_table(
        "video_tags",
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("video_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_tags")
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_videos_source_path"))
        batch_op.drop_index(batch_op.f("ix_videos_folder_id"))
        batch_op.drop_index(batch_op.f("ix_videos_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_videos_created_at"))

    op.drop_table("videos")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_prev_token_hash"))

    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_table("uploads")
    op.drop_table("tags")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_kind"))
        batch_op.drop_index(batch_op.f("ix_jobs_created_at"))

    op.drop_table("jobs")
    with op.batch_alter_table("folders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_folders_parent_id"))

    op.drop_table("folders")
    # ### end Alembic commands ###
